# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: blank # website title
first_name: Weijian
middle_name:
last_name: Lao
contact_note: >
  Ph.D. Candidate in Economics

description: >
  Academic website of Weijian Lao.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

keywords: economics, labor economics, land titling, development economics
lang: en
icon: ⚛️

url: https://laowj.github.io
baseurl: "" # 必须留空，保证根路径正确
last_updated: true
back_to_top: true

# -----------------------------------------------------------------------------
# Personal Information
# -----------------------------------------------------------------------------
email: "" # 可填入你的邮箱
socials:
  github: laowj
  googlescholar: "" # 填入你的 Google Scholar ID（如有）
